export const EXCEL_ARROW_DOWN = 'EXCEL_ARROW_DOWN';
export const EXCEL_ARROW_LEFT = 'EXCEL_ARROW_LEFT';
export const EXCEL_ARROW_RIGHT = 'EXCEL_ARROW_RIGHT';
export const EXCEL_ARROW_UP = 'EXCEL_ARROW_UP';

export const EXCEL_DELETE = 'EXCEL_DELETE';
export const EXCEL_ENTER = 'EXCEL_ENTER';

export const EXCEL_DELETE_CELLS_SHIFT_LEFT = 'EXCEL_DELETE_CELLS_SHIFT_LEFT';
export const EXCEL_DELETE_CELLS_SHIFT_UP = 'EXCEL_DELETE_CELLS_SHIFT_UP';
export const EXCEL_DOUBLE_CLICK_EDITABLE_CELL = 'EXCEL_DOUBLE_CLICK_EDITABLE_CELL';
export const EXCEL_RESIZE_COLUMN_START = 'EXCEL_RESIZE_COLUMN_START';
export const EXCEL_RESIZE_ROW_START = 'EXCEL_RESIZE_ROW_START';
export const EXCEL_ENABLE_EDIT_MODE = 'EXCEL_ENABLE_EDIT_MODE';
export const EXCEL_DISABLE_EDIT_MODE = 'EXCEL_DISABLE_EDIT_MODE';
export const EXCEL_ESCAPE = 'EXCEL_ESCAPE';

export const EXCEL_INSERT_COLUMN = 'EXCEL_INSERT_COLUMN';
export const EXCEL_INSERT_ROW = 'EXCEL_INSERT_ROW';

export const EXCEL_MOUSE_DOWN = 'EXCEL_MOUSE_DOWN';

export const EXCEL_SELECT_OVER = 'EXCEL_SELECT_OVER';

export const EXCEL_RIGHT_CLICK_CELL = 'EXCEL_RIGHT_CLICK_CELL';
export const EXCEL_SELECT_ALL = 'EXCEL_SELECT_ALL';
export const EXCEL_SELECT_COLUMN = 'EXCEL_SELECT_COLUMN';
export const EXCEL_SELECT_ROW = 'EXCEL_SELECT_ROW';
export const EXCEL_SET_BLOCK_STYLE = 'EXCEL_SET_BLOCK_STYLE';

export const EXCEL_SET_BUSINESS_CONCEPT = 'EXCEL_SET_BUSINESS_CONCEPT';
export const EXCEL_SET_GROUPS = 'EXCEL_SET_GROUPS';
export const EXCEL_SET_PREPOPULATE = 'EXCEL_SET_PREPOPULATE';

export const EXCEL_SET_SCROLL_DATA = 'EXCEL_SET_SCROLL_DATA';
export const EXCEL_SET_SHEET_NAME = 'EXCEL_SET_SHEET_NAME';
export const EXCEL_SET_SHEET = 'EXCEL_SET_SHEET';
export const EXCEL_TAB = 'EXCEL_TAB';

export const EXCEL_SET_EXCEL_DATA = 'EXCEL_SET_EXCEL_DATA';
export const EXCEL_RESET_EXCEL_DATA = 'EXCEL_RESET_EXCEL_DATA';

export const EXCEL_SET_NAME = 'EXCEL_SET_NAME';

export const EXCEL_TOGGLE_TEMPLATE_PUBLISH = 'EXCEL_TOGGLE_TEMPLATE_PUBLISH';

export const EXCEL_SET_ACTIVE_CELL_DIALOG = 'EXCEL_SET_ACTIVE_CELL_DIALOG';
export const EXCEL_RESET_ACTIVE_CELL_DIALOG = 'EXCEL_RESET_ACTIVE_CELL_DIALOG';

export const EXCEL_SET_ACTIVE_CELL_INPUT_VALUE = 'EXCEL_SET_ACTIVE_CELL_INPUT_VALUE';

export const EXCEL_SET_READ_ONLY = 'EXCEL_SET_READ_ONLY';
export const EXCEL_UNSET_READ_ONLY = 'EXCEL_UNSET_READ_ONLY';

export const EXCEL_DOWNLOAD = 'EXCEL_DOWNLOAD';
export const EXCEL_SAVE = 'EXCEL_SAVE';

export const EXCEL_ADD_COMMENT = 'EXCEL_ADD_COMMENT';
export const EXCEL_DELETE_COMMENT = 'EXCEL_DELETE_COMMENT';

export const EXCEL_ENABLE_SHEET_FOCUS = 'EXCEL_ENABLE_SHEET_FOCUS';
export const EXCEL_DISABLE_SHEET_FOCUS = 'EXCEL_DISABLE_SHEET_FOCUS';

export const EXCEL_MERGE_CELLS = 'EXCEL_MERGE_CELLS';
export const EXCEL_UNMERGE_CELLS = 'EXCEL_UNMERGE_CELLS';

export const EXCEL_RESIZE_ROW = 'EXCEL_RESIZE_ROW';
export const EXCEL_RESIZE_COLUMN = 'EXCEL_RESIZE_COLUMN';

export const EXCEL_SELECT_END = 'EXCEL_SELECT_END';

export const EXCEL_RESIZE_ROW_END = 'EXCEL_RESIZE_ROW_END';
export const EXCEL_RESIZE_COLUMN_END = 'EXCEL_RESIZE_COLUMN_END';
